### ISSUE TITLE
Absolute path for YABAR_THERMAL

### ISSUE THREAD

**Issue by jacksgt** [yabar-dev/yabar-fork#3]
We should switch from using `NAME` as the `internal-option1` for [YABAR_THERMAL](https://github.com/yabar-dev/yabar/wiki/Internal-Blocks#yabar_thermal) (and then expanding to `/sys/class/thermal/NAME/temp`) to directly specifying the full absolute path in the config file.

https://github.com/yabar-dev/yabar/blob/master/src/intern_blks/ya_intern.c#L105

This will provide more flexibility (that way any file can be specified, as long as it has the correct format).

**Comment by jacksgt** [comment]
Also, same for [YABAR_BRIGHTNESS]():

https://github.com/yabar-dev/yabar/blob/master/src/intern_blks/ya_intern.c#L179

**Comment by NBonaparte** [comment]
This should be an easy fix, right? I'd say just go ahead and do it.

**Comment by jacksgt** [comment]
Indeed, but no today ;-)

**Comment by jacksgt** [comment]
Just FYI:
I created a new repository [yabar]() (and renamed this one to [yabar-fork]() ), because forked GitHub repos have some restrictions (e.g. not searchable etc.). I thought I'd rather do that now than later.

This issues is fixed with commit https://github.com/yabar-dev/yabar/commit/e925584d99deb5cd5f41c0be2ddd270ed363653e

I also updated [the documentation](https://github.com/yabar-dev/yabar/wiki/Internal-Blocks) accordingly.
